"""Epistemic aggregate and repository protocols."""
from __future__ import annotations

from collections.abc import Mapping
from datetime import date
from typing import Protocol

from .model import (
    Analysis,
    Assumption,
    Claim,
    DeadEnd,
    Discovery,
    IndependenceGroup,
    PairwiseSeparation,
    Parameter,
    Prediction,
    Theory,
)
from .types import (
    AnalysisId,
    AssumptionId,
    ClaimId,
    ClaimStatus,
    DeadEndId,
    DeadEndStatus,
    DiscoveryId,
    DiscoveryStatus,
    IndependenceGroupId,
    ParameterId,
    PairwiseSeparationId,
    PredictionId,
    PredictionStatus,
    TheoryId,
    TheoryStatus,
)


class EpistemicWebPort(Protocol):
    """Dependency-inversion point for the epistemic web aggregate."""

    version: int

    claims: Mapping[ClaimId, Claim]
    assumptions: Mapping[AssumptionId, Assumption]
    predictions: Mapping[PredictionId, Prediction]
    theories: Mapping[TheoryId, Theory]
    discoveries: Mapping[DiscoveryId, Discovery]
    analyses: Mapping[AnalysisId, Analysis]
    independence_groups: Mapping[IndependenceGroupId, IndependenceGroup]
    pairwise_separations: Mapping[PairwiseSeparationId, PairwiseSeparation]
    dead_ends: Mapping[DeadEndId, DeadEnd]
    parameters: Mapping[ParameterId, Parameter]

    def get_claim(self, cid: ClaimId) -> Claim | None: ...
    def get_assumption(self, aid: AssumptionId) -> Assumption | None: ...
    def get_prediction(self, pid: PredictionId) -> Prediction | None: ...

    def claims_using_assumption(self, aid: AssumptionId) -> set[ClaimId]: ...
    def claim_lineage(self, cid: ClaimId) -> set[ClaimId]: ...
    def assumption_lineage(self, cid: ClaimId) -> set[AssumptionId]: ...
    def prediction_implicit_assumptions(self, pid: PredictionId) -> set[AssumptionId]: ...
    def refutation_impact(self, pid: PredictionId) -> dict[str, set]: ...
    def assumption_support_status(self, aid: AssumptionId) -> dict[str, set]: ...
    def claims_depending_on_claim(self, cid: ClaimId) -> set[ClaimId]: ...
    def predictions_depending_on_claim(self, cid: ClaimId) -> set[PredictionId]: ...
    def parameter_impact(self, pid: ParameterId) -> dict[str, set]: ...

    def register_claim(self, claim: Claim) -> EpistemicWebPort: ...
    def register_assumption(self, assumption: Assumption) -> EpistemicWebPort: ...
    def register_prediction(self, prediction: Prediction) -> EpistemicWebPort: ...
    def register_analysis(self, analysis: Analysis) -> EpistemicWebPort: ...
    def register_theory(self, theory: Theory) -> EpistemicWebPort: ...
    def register_independence_group(self, group: IndependenceGroup) -> EpistemicWebPort: ...
    def register_discovery(self, discovery: Discovery) -> EpistemicWebPort: ...
    def register_dead_end(self, dead_end: DeadEnd) -> EpistemicWebPort: ...
    def register_parameter(self, parameter: Parameter) -> EpistemicWebPort: ...
    def add_pairwise_separation(self, sep: PairwiseSeparation) -> EpistemicWebPort: ...

    def update_claim(self, new_claim: Claim) -> EpistemicWebPort: ...
    def update_assumption(self, new_assumption: Assumption) -> EpistemicWebPort: ...
    def update_prediction(self, new_prediction: Prediction) -> EpistemicWebPort: ...
    def update_parameter(self, new_parameter: Parameter) -> EpistemicWebPort: ...
    def update_analysis(self, new_analysis: Analysis) -> EpistemicWebPort: ...
    def update_theory(self, new_theory: Theory) -> EpistemicWebPort: ...
    def update_independence_group(self, new_group: IndependenceGroup) -> EpistemicWebPort: ...
    def update_pairwise_separation(self, new_sep: PairwiseSeparation) -> EpistemicWebPort: ...
    def update_discovery(self, new_discovery: Discovery) -> EpistemicWebPort: ...
    def update_dead_end(self, new_dead_end: DeadEnd) -> EpistemicWebPort: ...

    def transition_prediction(self, pid: PredictionId, new_status: PredictionStatus) -> EpistemicWebPort: ...
    def transition_dead_end(self, did: DeadEndId, new_status: DeadEndStatus) -> EpistemicWebPort: ...
    def transition_claim(self, cid: ClaimId, new_status: ClaimStatus) -> EpistemicWebPort: ...
    def transition_theory(self, tid: TheoryId, new_status: TheoryStatus) -> EpistemicWebPort: ...
    def transition_discovery(self, did: DiscoveryId, new_status: DiscoveryStatus) -> EpistemicWebPort: ...

    def record_analysis_result(
        self,
        anid: AnalysisId,
        result: object,
        *,
        git_sha: str | None = None,
        result_date: date | None = None,
    ) -> EpistemicWebPort: ...

    def remove_prediction(self, pid: PredictionId) -> EpistemicWebPort: ...
    def remove_claim(self, cid: ClaimId) -> EpistemicWebPort: ...
    def remove_assumption(self, aid: AssumptionId) -> EpistemicWebPort: ...
    def remove_parameter(self, pid: ParameterId) -> EpistemicWebPort: ...
    def remove_analysis(self, anid: AnalysisId) -> EpistemicWebPort: ...
    def remove_independence_group(self, gid: IndependenceGroupId) -> EpistemicWebPort: ...
    def remove_theory(self, tid: TheoryId) -> EpistemicWebPort: ...
    def remove_discovery(self, did: DiscoveryId) -> EpistemicWebPort: ...
    def remove_dead_end(self, did: DeadEndId) -> EpistemicWebPort: ...
    def remove_pairwise_separation(self, sid: PairwiseSeparationId) -> EpistemicWebPort: ...


class WebRepository(Protocol):
    """Load and save the epistemic web."""

    def load(self) -> EpistemicWebPort:
        """Deserialize and return the full epistemic web from storage."""
        ...

    def save(self, web: EpistemicWebPort) -> None:
        """Serialize and persist the epistemic web to storage."""
        ...

    @property
    def supports_native_validation(self) -> bool:
        """True if the backend can run domain validation natively."""
        return False


__all__ = ["EpistemicWebPort", "WebRepository"]